name: raqamliavloduz

services:

  backend:
    # image: ghcr.io/developer4o4/raqamliavloduz/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "15003:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      RAQAMLIAVLOD_DATABASE_NAME: ${POSTGRES_DB}
      RAQAMLIAVLOD_DATABASE_USERNAME: ${POSTGRES_USER}
      RAQAMLIAVLOD_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      PGBOUNCER_HOST: postgres
      PGBOUNCER_PORT: 5432
      BOT_SECRET: ${BOT_SECRET}
    volumes:
      - ./media:/app/media
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:15003
    environment:
      VITE_BACKEND_URL: http://localhost:15003
    ports:
      - "15002:3000"

  postgres:
    image: postgres:16-alpine
    container_name: raqamliavloduz-postgres  # ← fixed nom
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
      BACKEND_URL: http://backend:8000
      BOT_SECRET: ${BOT_SECRET}
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
