#!/bin/sh
set -e

if [ -n "$DJANGO_SECRET_KEY_FILE" ] && [ -f "$DJANGO_SECRET_KEY_FILE" ]; then
  export DJANGO_SECRET_KEY=$(cat "$DJANGO_SECRET_KEY_FILE")
fi

if [ -n "$RAQAMLIAVLOD_DATABASE_NAME_FILE" ] && [ -f "$RAQAMLIAVLOD_DATABASE_NAME_FILE" ]; then
  export RAQAMLIAVLOD_DATABASE_NAME=$(cat "$RAQAMLIAVLOD_DATABASE_NAME_FILE")
fi

if [ -n "$RAQAMLIAVLOD_DATABASE_USERNAME_FILE" ] && [ -f "$RAQAMLIAVLOD_DATABASE_USERNAME_FILE" ]; then
  export RAQAMLIAVLOD_DATABASE_USERNAME=$(cat "$RAQAMLIAVLOD_DATABASE_USERNAME_FILE")
fi

if [ -n "$RAQAMLIAVLOD_DATABASE_PASSWORD_FILE" ] && [ -f "$RAQAMLIAVLOD_DATABASE_PASSWORD_FILE" ]; then
  export RAQAMLIAVLOD_DATABASE_PASSWORD=$(cat "$RAQAMLIAVLOD_DATABASE_PASSWORD_FILE")
fi

python3 manage.py migrate --noinput

exec "$@"
