# Generated by Django 5.2.8 on 2025-12-08 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Meta')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('short_description', models.TextField(max_length=255, verbose_name='Kontest haqida qisqacha')),
                ('description', models.TextField(max_length=16000, verbose_name='Kontest haqida')),
                ('image', models.ImageField(upload_to='images/contest')),
                ('is_listed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contestlar',
                'db_table': 'contests',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Meta')),
                ('short_description', models.TextField(max_length=256, verbose_name='Masala haqida qisqacha')),
                ('description', models.TextField(max_length=16000, verbose_name='Masala haqida')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Oson'), (2, "O'rtacha"), (3, 'Qiyin'), (4, 'Juda qiyin')], default=1)),
                ('score', models.PositiveSmallIntegerField(default=5)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_tasks', to='contests.contestmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskDataModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('memory', models.PositiveBigIntegerField()),
                ('timeout', models.PositiveBigIntegerField()),
                ('output', models.TextField()),
                ('input', models.TextField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_data', to='contests.taskmodel')),
            ],
            options={
                'verbose_name': 'Masala malumoti',
                'verbose_name_plural': 'Masala',
                'db_table': 'task_datas',
            },
        ),
        migrations.CreateModel(
            name='UserContestRelationModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('score', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('disqualified_at', models.DateTimeField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_relations', to='contests.contestmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contestrelation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
