# Generated by Django 5.2.8 on 2025-12-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestmodel',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
