# Generated by Django 5.2.8 on 2025-12-07 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('title', models.CharField(max_length=32, verbose_name='Tur nomi')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Maqola turi',
                'verbose_name_plural': 'Maqola turlari',
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Meta')),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='images/articles')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articlecategorymodel')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleRateModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('rate', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rated', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_rates', to='articles.articlesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleCommentModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('dislikes', models.PositiveBigIntegerField(default=0)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='articles.articlesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
