# Generated by Django 5.2.8 on 2025-12-07 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('thumbnail', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Meta')),
                ('short_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Kurs haqida qisqacha')),
                ('description', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Kurs haqida')),
                ('is_new', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('source', models.CharField(max_length=64, unique=True, verbose_name='YouTube embeded link')),
                ('description', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Darslik haqida')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='courses.coursemodel')),
            ],
            options={
                'verbose_name': 'Darslik',
                'verbose_name_plural': 'Darsliklar',
                'db_table': 'lessons',
            },
        ),
    ]
