# Generated by Django 5.2.8 on 2025-12-08 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseRelationModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('is_course_over', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relations', to='courses.coursemodel')),
                ('current_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_lesson', to='courses.lessonmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courserelation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
