# Generated by Django 5.2.8 on 2025-12-07 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('thumbnail', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Meta')),
                ('source', models.CharField(max_length=512, verbose_name='Silka (Resurs)')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
            },
        ),
    ]
