/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumIndexRouteImport } from './routes/forum/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as ContestIndexRouteImport } from './routes/contest/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ContestSlugIndexRouteImport } from './routes/contest/$slug/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestIndexRoute = ContestIndexRouteImport.update({
  id: '/contest/',
  path: '/contest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestSlugIndexRoute = ContestSlugIndexRouteImport.update({
  id: '/contest/$slug/',
  path: '/contest/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course/$slug': typeof CourseSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/contest/': typeof ContestIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/contest/$slug/': typeof ContestSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course/$slug': typeof CourseSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/contest': typeof ContestIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/forum': typeof ForumIndexRoute
  '/contest/$slug': typeof ContestSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course/$slug': typeof CourseSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/contest/': typeof ContestIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/contest/$slug/': typeof ContestSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/course/$slug'
    | '/news/$slug'
    | '/articles/'
    | '/contest/'
    | '/courses/'
    | '/forum/'
    | '/contest/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/course/$slug'
    | '/news/$slug'
    | '/articles'
    | '/contest'
    | '/courses'
    | '/forum'
    | '/contest/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/course/$slug'
    | '/news/$slug'
    | '/articles/'
    | '/contest/'
    | '/courses/'
    | '/forum/'
    | '/contest/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProfileRoute: typeof ProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CourseSlugRoute: typeof CourseSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ContestIndexRoute: typeof ContestIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  ContestSlugIndexRoute: typeof ContestSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/': {
      id: '/contest/'
      path: '/contest'
      fullPath: '/contest/'
      preLoaderRoute: typeof ContestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$slug/': {
      id: '/contest/$slug/'
      path: '/contest/$slug'
      fullPath: '/contest/$slug/'
      preLoaderRoute: typeof ContestSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProfileRoute: ProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CourseSlugRoute: CourseSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ContestIndexRoute: ContestIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  ContestSlugIndexRoute: ContestSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
