# Generated by Django 5.2.8 on 2025-12-07 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Meta')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forumlar',
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='ForumAnswerModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Takrorlanmas ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sana')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_forumanswer', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_forum', to='forum.forummodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
